version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: apiuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: konecta
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      DATABASE_URL: postgres://apiuser:mypassword@db:5432/konecta
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - db
